vim.g["pandoc#syntax#conceal#blacklist"] = {
    --"titleblock",
    "image",
    "block",
    "subscript",
    "superscript",
    "strikeout",
    -- "atx",
    -- "codeblock_start",
    -- "codeblock_delim",
    "footnote",
    "definition",
    "list",
    "newline",
    "dashes",
    "ellipses",
    -- "quotes",
    -- "inlinecode",
    "inlinemath",
}
